{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "9dd6ff4e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Iniciando procesamiento de vigas y columnas...\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:416913' (GlobalId: 1YMpECnoXAAgd3TsblgkRb). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:416923' (GlobalId: 1YMpECnoXAAgd3TsblgkRl). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:418561' (GlobalId: 2e3KIcTBT93wdBtSLDrMFt). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:418605' (GlobalId: 2e3KIcTBT93wdBtSLDrMFR). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:418641' (GlobalId: 2e3KIcTBT93wdBtSLDrMEd). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:418970' (GlobalId: 2e3KIcTBT93wdBtSLDrMHi). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:419007' (GlobalId: 2e3KIcTBT93wdBtSLDrMH9). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:419117' (GlobalId: 2e3KIcTBT93wdBtSLDrMNR). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:419119' (GlobalId: 2e3KIcTBT93wdBtSLDrMNP). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:419128' (GlobalId: 2e3KIcTBT93wdBtSLDrMNE). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:419136' (GlobalId: 2e3KIcTBT93wdBtSLDrMMs). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:419138' (GlobalId: 2e3KIcTBT93wdBtSLDrMMq). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:419181' (GlobalId: 2e3KIcTBT93wdBtSLDrMMR). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:419183' (GlobalId: 2e3KIcTBT93wdBtSLDrMMP). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:419190' (GlobalId: 2e3KIcTBT93wdBtSLDrMM0). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:419198' (GlobalId: 2e3KIcTBT93wdBtSLDrMM8). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:419200' (GlobalId: 2e3KIcTBT93wdBtSLDrMLs). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:200x200:419918' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z4Q). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:200x200:419920' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z44). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:200x200:419927' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z43). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:200x200:419929' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z4D). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:200x200:419931' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z4F). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:200x200:419933' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z49). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:200x200:419935' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z4B). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:200x200:419941' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z4n). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:200x200:419943' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z4p). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:200x200:419947' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z4$). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:200x200:419949' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z4v). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:200x200:419951' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z4x). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:200x200:419957' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z4X). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:200x200:419959' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z4Z). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:200x200:419963' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z4l). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:200x200:419965' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z4f). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:200x200:419967' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z4h). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:420121' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z1D). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:420123' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z1F). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:420130' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z1s). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:420132' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z1m). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:420134' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z1o). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:420136' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z1y). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:420138' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z1_). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:420144' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z1a). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:420146' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z1c). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:420150' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z1Y). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:420152' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z1i). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:420154' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z1k). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:420160' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z0K). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:420162' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z0M). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:420166' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z0I). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:420168' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z0S). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular Beam:250 x 500mm:420170' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z0U). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular-Column:250 x 450 mm2:416794' (GlobalId: 1YMpECnoXAAgd3TsblgkPk). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular-Column:250 x 450 mm2:416796' (GlobalId: 1YMpECnoXAAgd3TsblgkPe). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular-Column:250 x 400 mm:416802' (GlobalId: 1YMpECnoXAAgd3TsblgkPM). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular-Column:250 x 450 mm2:416804' (GlobalId: 1YMpECnoXAAgd3TsblgkPG). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular-Column:300 x 400 mm2:418173' (GlobalId: 2e3KIcTBT93wdBtSLDrM6B). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular-Column:300 x 400 mm2:418273' (GlobalId: 2e3KIcTBT93wdBtSLDrM4N). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular-Column:250 x 450 mm2:419111' (GlobalId: 2e3KIcTBT93wdBtSLDrMNH). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular-Column:250 x 400 mm:419113' (GlobalId: 2e3KIcTBT93wdBtSLDrMNV). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular-Column:300 x 400 mm2:419125' (GlobalId: 2e3KIcTBT93wdBtSLDrMN3). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular-Column:250 x 450 mm2:419175' (GlobalId: 2e3KIcTBT93wdBtSLDrMMH). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular-Column:250 x 400 mm:419177' (GlobalId: 2e3KIcTBT93wdBtSLDrMMV). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular-Column:300 x 400 mm2:419187' (GlobalId: 2e3KIcTBT93wdBtSLDrMM5). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular-Column:250 x 450 mm2:420113' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z15). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular-Column:250 x 450 mm2:420115' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z17). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular-Column:250 x 400 mm:420117' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z11). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular-Column:250 x 450 mm2:420119' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z13). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular-Column:300 x 400 mm2:420126' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z1A). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular-Column:300 x 400 mm2:420128' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z1q). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular-Column:250 x 450 mm2:420140' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z1u). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular-Column:250 x 400 mm:420142' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z1w). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular-Column:300 x 400 mm2:420148' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z1W). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular-Column:250 x 450 mm2:420156' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z1e). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular-Column:250 x 400 mm:420158' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z1g). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn 'M_Concrete-Rectangular-Column:300 x 400 mm2:420164' (GlobalId: 0Bl0khqE5CRu4G24Ko5Z0G). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Procesados 0 elementos 'frame' (vigas/columnas).\n",
      "\n",
      "Iniciando procesamiento de muros y losas...\n",
      "Advertencia: No se pudo procesar el elemento IfcWall/IfcSlab 'Floor:Generic 200mm:422017' (GlobalId: 3aTnDTRUf3aPpeHNVYb1bz). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Advertencia: No se pudo procesar el elemento IfcWall/IfcSlab 'Floor:Generic 200mm:424327' (GlobalId: 3aTnDTRUf3aPpeHNVYb11x). Error: 'TriangulationElement' object has no attribute 'bbox'\n",
      "Procesados 0 elementos 'shell' (muros/losas).\n",
      "\n",
      "Script de OpenSeesPy generado en 'model_opensees.py'\n",
      "\n",
      "Proceso de conversión completado.\n"
     ]
    }
   ],
   "source": [
    "import ifcopenshell\n",
    "import ifcopenshell.geom as geom\n",
    "import numpy as np\n",
    "import uuid\n",
    "\n",
    "# --- Configuración de ifcopenshell.geom ---\n",
    "# Necesario para el procesamiento geométrico\n",
    "settings = geom.settings()\n",
    "\n",
    "class IfcToOpenSeesConverter:\n",
    "    def __init__(self, ifc_file_path):\n",
    "        self.model = ifcopenshell.open(ifc_file_path)\n",
    "        self.nodes_map = {}  # Mapea tuplas de coordenadas a IDs de nodos OpenSees\n",
    "        self.next_node_id = 1\n",
    "        self.opensees_commands = []\n",
    "        self.node_tolerance = 0.01  # Tolerancia para agrupar nodos (en unidades del modelo IFC)\n",
    "\n",
    "    def add_opensees_command(self, command):\n",
    "        self.opensees_commands.append(command)\n",
    "\n",
    "    def get_or_create_node(self, coords):\n",
    "        \"\"\"\n",
    "        Obtiene un ID de nodo OpenSees para las coordenadas dadas.\n",
    "        Si las coordenadas ya existen (dentro de la tolerancia), devuelve su ID.\n",
    "        De lo contrario, crea un nuevo nodo y devuelve su ID.\n",
    "        \"\"\"\n",
    "        # Redondea las coordenadas para la comparación de tolerancia\n",
    "        rounded_coords = tuple(round(c, 5) for c in coords) # 5 decimales de precisión\n",
    "\n",
    "        for existing_coords, node_id in self.nodes_map.items():\n",
    "            if np.linalg.norm(np.array(rounded_coords) - np.array(existing_coords)) < self.node_tolerance:\n",
    "                return node_id\n",
    "\n",
    "        # Si no se encontró, crea un nuevo nodo\n",
    "        node_id = self.next_node_id\n",
    "        self.nodes_map[rounded_coords] = node_id\n",
    "        self.next_node_id += 1\n",
    "        self.add_opensees_command(f\"ops.node({node_id}, {coords[0]:.3f}, {coords[1]:.3f}, {coords[2]:.3f})\")\n",
    "        return node_id\n",
    "\n",
    "    def extract_material_properties(self, ifc_element):\n",
    "        \"\"\"\n",
    "        Intenta extraer propiedades del material asociadas al elemento.\n",
    "        Esto es muy simplificado; en un caso real, necesitarías navegar por\n",
    "        IfcRelAssociatesMaterial, IfcMaterialDefinitionSet, IfcMaterialProperties, etc.\n",
    "        \"\"\"\n",
    "        # Por ahora, devuelve un material genérico.\n",
    "        # Implementa aquí la lógica para buscar IfcMaterial o IfcMaterialProperties\n",
    "        # y mapearlas a un material de OpenSees.\n",
    "        # Puedes buscar en ifc_element.IsTypedBy.RelatedByType o ifc_element.IsDefinedBy.RelatedDefiners\n",
    "        return {'E': 2.0e11, 'nu': 0.3, 'rho': 7850.0} # Acero por defecto\n",
    "\n",
    "    def extract_section_properties(self, ifc_element):\n",
    "        \"\"\"\n",
    "        Intenta extraer las propiedades de la sección transversal.\n",
    "        Muy simplificado; necesitas buscar IfcRelDefinesByProperties, IfcSectionProperties,\n",
    "        IfcProfileDef (IfcRectangleProfileDef, IfcIProfileDef, etc.)\n",
    "        \"\"\"\n",
    "        # Por ahora, devuelve propiedades genéricas.\n",
    "        # Implementa aquí la lógica para buscar IfcProfileDef y calcular A, Ixx, Iyy, J.\n",
    "        # Ejemplo: Para una viga rectangular de 0.3x0.6\n",
    "        if 'Beam' in ifc_element.is_a() or 'Column' in ifc_element.is_a():\n",
    "             # Intenta buscar un perfil. Esto es un placeholder.\n",
    "            # Necesitarías recorrer ifc_element.IsTypedBy, etc.\n",
    "            return {'A': 0.3 * 0.6, 'Ixx': (0.3 * 0.6**3) / 12, 'Iyy': (0.6 * 0.3**3) / 12, 'G': None, 'J': None}\n",
    "        return {'A': 1.0, 'Ixx': 1.0, 'Iyy': 1.0, 'G': None, 'J': None} # Valores por defecto\n",
    "\n",
    "    def process_beams_and_columns(self):\n",
    "        linear_elements = self.model.by_type('IfcBeam') + self.model.by_type('IfcColumn')\n",
    "        frame_elements_count = 0\n",
    "        self.add_opensees_command(\"\\n# --- Definicion de Materiales OpenSees (simplificado) ---\")\n",
    "        self.add_opensees_command(\"ops.uniaxialMaterial('Elastic', 1, 2.0e11) # ID 1 para material generico\") # Ajustar esto\n",
    "\n",
    "        self.add_opensees_command(\"\\n# --- Definicion de Secciones (transformaciones de seccion) ---\")\n",
    "        # Ejemplo de transformación de sección para elementos frame\n",
    "        self.add_opensees_command(\"ops.geomTransf('Linear', 1) # ID 1 para transformacion generica\")\n",
    "\n",
    "        self.add_opensees_command(\"\\n# --- Elementos Frame (Vigas y Columnas) ---\")\n",
    "\n",
    "        for i, element in enumerate(linear_elements):\n",
    "            try:\n",
    "                # Intenta obtener la línea central del elemento\n",
    "                # Esto es una simplificación. ifcopenshell.geom.tessellate es para mallas,\n",
    "                # para líneas centrales se necesita más procesamiento del IfcProductDefinitionShape.\n",
    "                # Una forma común es buscar IfcProduct.Representation.Representations[0].Item[0]\n",
    "                # que podría ser un IfcPolyline o IfcArbitraryOpenProfileDef.\n",
    "                \n",
    "                # Por simplicidad, intentaremos obtener la bounding box y usar su centro\n",
    "                # Esto NO es una línea de eje precisa, solo una aproximación para el ejemplo.\n",
    "                # Para un control preciso, necesitas analizar IfcAxis2Placement3D\n",
    "                # y las curvas de extrusión o las representaciones de línea.\n",
    "                \n",
    "                # ifcopenshell.geom.utils no tiene una forma directa de obtener lineas de eje\n",
    "                # Esto requeriría una implementación más profunda de la geometría\n",
    "                \n",
    "                # Una alternativa es usar las propiedades de la Pset_BeamCommon o Pset_ColumnCommon\n",
    "                # si existen, para encontrar puntos de inicio/fin, pero no es universal.\n",
    "\n",
    "                # Fallback: Usar los puntos de inicio/fin de la línea de extrusión si disponible\n",
    "                # O la línea del IfcCurve geométrica asociada\n",
    "                if element.ObjectPlacement and element.ObjectPlacement.RelativePlacement:\n",
    "                    # Intenta extraer el origen y la dirección principal\n",
    "                    placement = element.ObjectPlacement.RelativePlacement\n",
    "                    origin = placement.Location.Coordinates\n",
    "                    \n",
    "                    # Para una viga/columna, a menudo son extrusiones.\n",
    "                    # Asumimos que la viga/columna se extiende a lo largo de un eje.\n",
    "                    # Esto es MUY simplificado.\n",
    "                    # Un enfoque más robusto implicaría usar el IfcGeometricRepresentationItem\n",
    "                    # y analizar IfcProductDefinitionShape para IfcExtrudedAreaSolid\n",
    "                    # y sacar el Axis de la extrusión.\n",
    "                    \n",
    "                    # Placeholder para start_point y end_point\n",
    "                    # Ejemplo: Usar los extremos de la bounding box si no hay otra forma\n",
    "                    product_shape = geom.create_shape(settings, element)\n",
    "                    bbox = product_shape.bbox() # [x_min, y_min, z_min, x_max, y_max, z_max]\n",
    "\n",
    "                    start_point = np.array([bbox[0], bbox[1], bbox[2]]) # esquina inf-izq-frontal\n",
    "                    end_point = np.array([bbox[3], bbox[4], bbox[5]])   # esquina sup-der-trasera\n",
    "\n",
    "                    # Para elementos lineales, intentamos usar el centro de dos caras opuestas o el centro de la extrusión\n",
    "                    # Esto es un gran desafío en IFC sin reglas claras de Revit.\n",
    "                    # Mejor aproximación: intentar usar la línea de extrusión si el elemento es IfcExtrudedAreaSolid\n",
    "                    \n",
    "                    if element.Representation and element.Representation.Representations:\n",
    "                        for rep in element.Representation.Representations:\n",
    "                            for item in rep.Items:\n",
    "                                if item.is_a('IfcExtrudedAreaSolid'):\n",
    "                                    extrusion_axis = item.ExtrudedDirection.DirectionRatios\n",
    "                                    extrusion_length = item.Depth\n",
    "                                    # Esto es el origen del perfil de la extrusión, no necesariamente el centro de la viga\n",
    "                                    # start_point_geom = item.SweptArea.RefDirection.Location.Coordinates \n",
    "                                    # end_point_geom = start_point_geom + np.array(extrusion_axis) * extrusion_length\n",
    "                                    \n",
    "                                    # Para este ejemplo, seguiremos con una aproximación de bounding box\n",
    "                                    # o mejor aún, si tuvieras los puntos de inicio/fin del modelo analítico de Revit\n",
    "                                    pass # Mantener los puntos del bounding box para este ejemplo\n",
    "\n",
    "                    # Si el elemento tiene un IfcCurve, se puede extraer directamente\n",
    "                    # Esto es lo ideal para la línea analítica\n",
    "                    # Por ejemplo, si el elemento IfcBeam está asociado a un IfcStructuralCurveMember\n",
    "                    # que tiene un IfcCurve.\n",
    "\n",
    "                    # Para este ejemplo, usaremos el centro de las caras opuestas de la bounding box para los puntos del elemento 'frame'.\n",
    "                    # Esto no es robusto para un análisis estructural preciso, pero sirve para la demostración.\n",
    "                    \n",
    "                    # Obtener el centro del bounding box\n",
    "                    center_x = (bbox[0] + bbox[3]) / 2\n",
    "                    center_y = (bbox[1] + bbox[4]) / 2\n",
    "                    center_z = (bbox[2] + bbox[5]) / 2\n",
    "\n",
    "                    # Suponemos que el elemento se extiende predominantemente en X o Y o Z\n",
    "                    # Vamos a simplificar y decir que el elemento va de un punto a otro.\n",
    "                    # La forma más simple es usar los extremos de la línea diagonal de la bounding box\n",
    "                    # o los centros de las caras opuestas.\n",
    "                    \n",
    "                    # Un enfoque más realista para la línea de eje:\n",
    "                    # Intenta encontrar el IfcAxis2Placement3D y la dirección de extrusión\n",
    "                    # Esto es un placeholder; la extracción real es más compleja.\n",
    "                    \n",
    "                    # Asumiremos puntos de inicio y fin dummy para el ejemplo que demuestren el flujo\n",
    "                    # En la vida real, los obtendrías de la geometría extrudida o la línea del modelo analítico\n",
    "                    \n",
    "                    start_point = np.array([bbox[0], (bbox[1]+bbox[4])/2, (bbox[2]+bbox[5])/2])\n",
    "                    end_point = np.array([bbox[3], (bbox[1]+bbox[4])/2, (bbox[2]+bbox[5])/2])\n",
    "                    \n",
    "                    # Si la viga/columna es más alta que ancha, podría estar en Z\n",
    "                    dim_x = bbox[3] - bbox[0]\n",
    "                    dim_y = bbox[4] - bbox[1]\n",
    "                    dim_z = bbox[5] - bbox[2]\n",
    "\n",
    "                    if dim_z > dim_x and dim_z > dim_y: # Predominantemente vertical (columna)\n",
    "                         start_point = np.array([(bbox[0]+bbox[3])/2, (bbox[1]+bbox[4])/2, bbox[2]])\n",
    "                         end_point = np.array([(bbox[0]+bbox[3])/2, (bbox[1]+bbox[4])/2, bbox[5]])\n",
    "                    elif dim_x > dim_y and dim_x > dim_z: # Predominantemente horizontal en X (viga)\n",
    "                         start_point = np.array([bbox[0], (bbox[1]+bbox[4])/2, (bbox[2]+bbox[5])/2])\n",
    "                         end_point = np.array([bbox[3], (bbox[1]+bbox[4])/2, (bbox[2]+bbox[5])/2])\n",
    "                    else: # Predominantemente horizontal en Y (viga)\n",
    "                         start_point = np.array([(bbox[0]+bbox[3])/2, bbox[1], (bbox[2]+bbox[5])/2])\n",
    "                         end_point = np.array([(bbox[0]+bbox[3])/2, bbox[4], (bbox[2]+bbox[5])/2])\n",
    "\n",
    "\n",
    "                    node_id_start = self.get_or_create_node(start_point)\n",
    "                    node_id_end = self.get_or_create_node(end_point)\n",
    "\n",
    "                    material_props = self.extract_material_properties(element)\n",
    "                    section_props = self.extract_section_properties(element)\n",
    "\n",
    "                    # ID de elemento único para OpenSees\n",
    "                    element_id = int(uuid.uuid4().int % 1000000) # Genera un ID \"aleatorio\"\n",
    "\n",
    "                    # Definición de elemento 'elasticBeamColumn' en OpenSeesPy\n",
    "                    # Los valores de propiedades A, E, G, J, Ixx, Iyy deben venir de section_props y material_props\n",
    "                    # G = E / (2 * (1 + nu))\n",
    "                    G_val = material_props['E'] / (2 * (1 + material_props['nu'])) if material_props['nu'] is not None else material_props['E'] / 2.6 # Estimación si nu es nulo\n",
    "                    \n",
    "                    self.add_opensees_command(\n",
    "                        f\"ops.element('elasticBeamColumn', {element_id}, \"\n",
    "                        f\"{node_id_start}, {node_id_end}, \"\n",
    "                        f\"{section_props['A']:.5f}, {material_props['E']:.0f}, \"\n",
    "                        f\"{G_val:.0f}, {section_props['J'] if section_props['J'] else 0.0:.5f}, \"\n",
    "                        f\"{section_props['Iyy']:.5f}, {section_props['Ixx']:.5f}, \"\n",
    "                        f\"1) # Ultimo 1 es el tag de la transformacion geometrica\"\n",
    "                    )\n",
    "                    frame_elements_count += 1\n",
    "\n",
    "            except Exception as e:\n",
    "                print(f\"Advertencia: No se pudo procesar el elemento IfcBeam/IfcColumn '{element.Name}' (GlobalId: {element.GlobalId}). Error: {e}\")\n",
    "                # Puedes loguear el error o saltar este elemento\n",
    "\n",
    "        print(f\"Procesados {frame_elements_count} elementos 'frame' (vigas/columnas).\")\n",
    "\n",
    "\n",
    "    def process_walls_and_slabs(self):\n",
    "        surface_elements = self.model.by_type('IfcWall') + self.model.by_type('IfcSlab')\n",
    "        shell_elements_count = 0\n",
    "        self.add_opensees_command(\"\\n# --- Elementos Shell (Muros y Losas) ---\")\n",
    "\n",
    "        for i, element in enumerate(surface_elements):\n",
    "            try:\n",
    "                # La extracción de la geometría de una superficie (plano medio, vértices)\n",
    "                # es más compleja. Ifcopenshell.geom.tessellate devuelve una malla (triángulos).\n",
    "                # Necesitamos extraer los vértices del contorno o el plano medio para un elemento 'shell'.\n",
    "                \n",
    "                # Una estrategia es obtener la malla y usar los vértices de la cara principal.\n",
    "                # Esto es una simplificación: asumiremos que cada elemento es una única superficie plana.\n",
    "                \n",
    "                # ifcopenshell.util.selector.get_representation es útil para obtener la geometría principal\n",
    "                # pero el procesamiento para obtener 4 vértices para un shell plano requiere análisis.\n",
    "                \n",
    "                product_shape = geom.create_shape(settings, element)\n",
    "                \n",
    "                if not product_shape.geometry:\n",
    "                    print(f\"Advertencia: No hay geometría disponible para {element.Name} (GlobalId: {element.GlobalId}).\")\n",
    "                    continue\n",
    "\n",
    "                # Intenta obtener los vértices del contorno principal de la superficie.\n",
    "                # Esto es MUY simplificado. Una pared o losa puede tener aberturas o formas complejas.\n",
    "                # Aquí, solo tomaremos los vértices de la malla más externa o principal.\n",
    "                \n",
    "                # Obtener los vértices de la malla (triangulación)\n",
    "                # Esto es útil para visualización, no directamente para elementos shell de OpenSees.\n",
    "                # Para un shell, necesitamos nodos en las esquinas.\n",
    "\n",
    "                # Si el elemento es un IfcPlate o IfcWall, el espesor puede ser una propiedad\n",
    "                # o derivado de la geometría.\n",
    "                thickness = None\n",
    "                # Intenta buscar una propiedad de espesor\n",
    "                for rel_def in element.IsDefinedBy:\n",
    "                    if rel_def.is_a('IfcRelDefinesByProperties'):\n",
    "                        prop_set = rel_def.RelatingPropertyDefinition\n",
    "                        if prop_set.is_a('IfcPropertySet'):\n",
    "                            for prop in prop_set.HasProperties:\n",
    "                                if prop.is_a('IfcPropertySingleValue') and prop.Name.lower() == 'thickness' and prop.NominalValue:\n",
    "                                    thickness = prop.NominalValue.wrappedValue\n",
    "                                    break\n",
    "                        elif prop_set.is_a('IfcElementQuantity'):\n",
    "                             for quantity in prop_set.Quantities:\n",
    "                                 if quantity.is_a('IfcQuantityLength') and quantity.Name.lower() == 'thickness':\n",
    "                                     thickness = quantity.LengthValue\n",
    "                                     break\n",
    "                    if thickness is not None:\n",
    "                        break\n",
    "                \n",
    "                if thickness is None:\n",
    "                    # Si no se encuentra, intentar inferir del bounding box\n",
    "                    bbox = product_shape.bbox()\n",
    "                    dims = [bbox[3]-bbox[0], bbox[4]-bbox[1], bbox[5]-bbox[2]]\n",
    "                    # El espesor será la dimensión más pequeña\n",
    "                    thickness = min(dims)\n",
    "                    if thickness < 0.001: # Si es demasiado delgado, asumir un valor por defecto o saltar\n",
    "                        thickness = 0.2 # Valor por defecto para paredes/losas si no se encuentra\n",
    "                        print(f\"Advertencia: Espesor no encontrado para {element.Name}. Usando valor por defecto: {thickness:.3f}m\")\n",
    "\n",
    "                \n",
    "                # Para un elemento Shell en OpenSees, necesitamos 4 nodos que definan un plano.\n",
    "                # Esto es difícil de generalizar desde IFC.\n",
    "                # Una aproximación: Obtener el centroide del bounding box y los puntos extremos de la cara principal.\n",
    "                \n",
    "                bbox = product_shape.bbox()\n",
    "                \n",
    "                # Asumimos que la cara principal es XY para losas o XZ/YZ para muros\n",
    "                # Genera 4 puntos representativos de la cara principal\n",
    "                # Esto es una HEURÍSTICA y podría no funcionar para todas las geometrías.\n",
    "                \n",
    "                # Muros (predominantemente verticales)\n",
    "                if 'Wall' in element.is_a():\n",
    "                    # Suponemos que un muro se extiende en X y Z (o Y y Z)\n",
    "                    # Y tiene un espesor en Y (o X)\n",
    "                    p1 = np.array([bbox[0], (bbox[1]+bbox[4])/2, bbox[2]])\n",
    "                    p2 = np.array([bbox[3], (bbox[1]+bbox[4])/2, bbox[2]])\n",
    "                    p3 = np.array([bbox[3], (bbox[1]+bbox[4])/2, bbox[5]])\n",
    "                    p4 = np.array([bbox[0], (bbox[1]+bbox[4])/2, bbox[5]])\n",
    "                # Losas (predominantemente horizontales)\n",
    "                elif 'Slab' in element.is_a():\n",
    "                    # Suponemos que una losa se extiende en X y Y\n",
    "                    # Y tiene un espesor en Z\n",
    "                    p1 = np.array([bbox[0], bbox[1], (bbox[2]+bbox[5])/2])\n",
    "                    p2 = np.array([bbox[3], bbox[1], (bbox[2]+bbox[5])/2])\n",
    "                    p3 = np.array([bbox[3], bbox[4], (bbox[2]+bbox[5])/2])\n",
    "                    p4 = np.array([bbox[0], bbox[4], (bbox[2]+bbox[5])/2])\n",
    "                else:\n",
    "                    continue # No se sabe cómo manejar este tipo de elemento de superficie\n",
    "\n",
    "                node_id1 = self.get_or_create_node(p1)\n",
    "                node_id2 = self.get_or_create_node(p2)\n",
    "                node_id3 = self.get_or_create_node(p3)\n",
    "                node_id4 = self.get_or_create_node(p4)\n",
    "\n",
    "                material_props = self.extract_material_properties(element)\n",
    "                \n",
    "                element_id = int(uuid.uuid4().int % 1000000) # Genera un ID \"aleatorio\"\n",
    "\n",
    "                # Definición de material para shell (usaremos el mismo ID 1 por simplicidad)\n",
    "                # En un caso real, definirías materiales específicos como PlateFiber o Section\n",
    "                \n",
    "                # OpenSees necesita un material para el shell\n",
    "                # Usaremos un material de hormigón genérico para el ejemplo\n",
    "                # self.add_opensees_command(f\"ops.nDMaterial('ElasticIsotropic', 2, {material_props['E']:.0f}, {material_props['nu']:.2f})\") # ID 2 para shell\n",
    "                # self.add_opensees_command(f\"ops.section('PlateFiber', {element_id}, 2, {thickness:.3f})\") # Sección delgada de placa, ID de sección es el mismo que el elemento\n",
    "\n",
    "                self.add_opensees_command(\n",
    "                    f\"ops.element('ShellDKGQ', {element_id}, \"\n",
    "                    f\"{node_id1}, {node_id2}, {node_id3}, {node_id4}, \"\n",
    "                    f\"1, {thickness:.3f}) # ID 1 es el material para el shell (simplificado)\"\n",
    "                )\n",
    "                shell_elements_count += 1\n",
    "\n",
    "            except Exception as e:\n",
    "                print(f\"Advertencia: No se pudo procesar el elemento IfcWall/IfcSlab '{element.Name}' (GlobalId: {element.GlobalId}). Error: {e}\")\n",
    "        \n",
    "        print(f\"Procesados {shell_elements_count} elementos 'shell' (muros/losas).\")\n",
    "\n",
    "\n",
    "    def generate_opensees_script(self, output_file=\"model_opensees.py\"):\n",
    "        \"\"\"\n",
    "        Genera el script de OpenSeesPy a partir de los comandos recolectados.\n",
    "        \"\"\"\n",
    "        with open(output_file, 'w') as f:\n",
    "            f.write(\"import openseespy.opensees as ops\\n\")\n",
    "            f.write(\"import numpy as np\\n\\n\")\n",
    "            f.write(\"ops.wipe()\\n\")\n",
    "            f.write(\"ops.model('3D', '-ndm', 3, '-ndf', 6)\\n\\n\")\n",
    "            \n",
    "            f.write(\"# --- Definición de Nodos ---\\n\")\n",
    "            # Los nodos ya se agregan cuando se crean para evitar duplicados\n",
    "            # Ahora solo los escribimos en el orden en que fueron creados\n",
    "            sorted_nodes = sorted(self.nodes_map.items(), key=lambda item: item[1])\n",
    "            for coords, node_id in sorted_nodes:\n",
    "                f.write(f\"ops.node({node_id}, {coords[0]:.3f}, {coords[1]:.3f}, {coords[2]:.3f})\\n\")\n",
    "            \n",
    "            # Escribir el resto de comandos (materiales, transformaciones, elementos)\n",
    "            for command in self.opensees_commands:\n",
    "                f.write(command + \"\\n\")\n",
    "            \n",
    "            f.write(\"\\n# --- Definición de Apoyos (Ejemplo: empotramiento en la base) ---\\n\")\n",
    "            f.write(\"# Esto es un ejemplo. Necesitarás identificar los nodos base de tus columnas.\\n\")\n",
    "            f.write(\"# for node_id, coords in converter.nodes_map.items():\\n\")\n",
    "            f.write(\"#     if coords[2] < 0.05: # Si el nodo está cerca del nivel z=0 (asumido como base)\\n\")\n",
    "            f.write(\"#         ops.fix(node_id, 1, 1, 1, 1, 1, 1) # Empotrado\\n\")\n",
    "            \n",
    "            f.write(\"\\n# --- Definición de Cargas (Ejemplo: gravedad) ---\\n\")\n",
    "            f.write(\"# ops.timeSeries('Linear', 1)\\n\")\n",
    "            f.write(\"# ops.pattern('Plain', 1, 1)\\n\")\n",
    "            f.write(\"# for node_id, coords in converter.nodes_map.items():\\n\")\n",
    "            f.write(\"#     if 'columna' in str(node_id): # Necesitas una forma de identificar los nodos de columna\\n\")\n",
    "            f.write(\"#         ops.load(node_id, 0.0, 0.0, -10.0, 0.0, 0.0, 0.0) # Carga axial en columnas\\n\")\n",
    "\n",
    "            f.write(\"\\n# --- Análisis (Ejemplo: estático) ---\\n\")\n",
    "            f.write(\"# ops.constraints('Plain')\\n\")\n",
    "            f.write(\"# ops.numberer('RCM')\\n\")\n",
    "            f.write(\"# ops.system('BandSPD')\\n\")\n",
    "            f.write(\"# ops.integrator('LoadControl', 0.1)\\n\")\n",
    "            f.write(\"# ops.algorithm('Newton')\\n\")\n",
    "            f.write(\"# ops.analysis('Static')\\n\")\n",
    "            f.write(\"# ops.analyze(10) # 10 pasos de carga\\n\")\n",
    "            f.write(\"# ops.printModel('-JSON', 'model.json')\\n\")\n",
    "\n",
    "        print(f\"\\nScript de OpenSeesPy generado en '{output_file}'\")\n",
    "\n",
    "\n",
    "# --- Uso del Convertidor ---\n",
    "if __name__ == \"__main__\":\n",
    "    ifc_file = \"sample_models/CASA TIPO 11111.ifc\" # ¡CAMBIA ESTO A LA RUTA DE TU ARCHIVO IFC!\n",
    "\n",
    "    try:\n",
    "        converter = IfcToOpenSeesConverter(ifc_file)\n",
    "        \n",
    "        print(\"\\nIniciando procesamiento de vigas y columnas...\")\n",
    "        converter.process_beams_and_columns()\n",
    "        \n",
    "        print(\"\\nIniciando procesamiento de muros y losas...\")\n",
    "        converter.process_walls_and_slabs()\n",
    "        \n",
    "        converter.generate_opensees_script()\n",
    "        print(\"\\nProceso de conversión completado.\")\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"\\n¡Ocurrió un error general! Asegúrate de que el archivo IFC exista y sea válido.\")\n",
    "        print(f\"Error: {e}\")\n",
    "        import traceback\n",
    "        traceback.print_exc()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b7da599a",
   "metadata": {},
   "outputs": [],
   "source": [
    "import clr\n",
    "clr.AddReference(\"RevitAPI\")\n",
    "clr.AddReference(\"RevitAPIUI\")\n",
    "from Autodesk.Revit.DB import *\n",
    "from Autodesk.Revit.DB.Structure import *\n",
    "from Autodesk.Revit.UI import *\n",
    "import RevitServices\n",
    "from RevitServices.Persistence import DocumentManager\n",
    "from RevitServices.Transactions import TransactionManager\n",
    "import json\n",
    "import sys\n",
    "\n",
    "# Obtener el documento actual\n",
    "doc = DocumentManager.Instance.CurrentDBDocument\n",
    "\n",
    "# Inicializar diccionario para datos\n",
    "analytical_data = {\n",
    "    \"nodes\": [],\n",
    "    \"frames\": [],\n",
    "    \"shells\": []\n",
    "}\n",
    "\n",
    "# Diccionario para nodos únicos\n",
    "node_dict = {}  # Clave: tupla (x,y,z), Valor: info del nodo\n",
    "node_counter = 0\n",
    "\n",
    "# --- Función para obtener propiedades del elemento ---\n",
    "def get_element_properties(element):\n",
    "    props = {}\n",
    "    if not element:\n",
    "        return props\n",
    "    \n",
    "    # Propiedades básicas\n",
    "    props[\"Name\"] = element.Name if hasattr(element, 'Name') else \"N/A\"\n",
    "    props[\"Category\"] = element.Category.Name if element.Category else \"N/A\"\n",
    "    \n",
    "    # Parámetros del elemento\n",
    "    for param in element.GetOrderedParameters():\n",
    "        if param.HasValue:\n",
    "            try:\n",
    "                if param.StorageType == StorageType.Double:\n",
    "                    props[param.Definition.Name] = param.AsDouble()\n",
    "                elif param.StorageType == StorageType.Integer:\n",
    "                    props[param.Definition.Name] = param.AsInteger()\n",
    "                elif param.StorageType == StorageType.String:\n",
    "                    props[param.Definition.Name] = param.AsString()\n",
    "                elif param.StorageType == StorageType.ElementId:\n",
    "                    props[param.Definition.Name] = param.AsElementId().IntegerValue\n",
    "            except:\n",
    "                continue\n",
    "    \n",
    "    # Propiedades del tipo si existe\n",
    "    if hasattr(element, 'GetTypeId'):\n",
    "        type_id = element.GetTypeId()\n",
    "        if type_id != ElementId.InvalidElementId:\n",
    "            type_element = doc.GetElement(type_id)\n",
    "            if type_element:\n",
    "                props[\"Type Name\"] = type_element.Name\n",
    "                # Materiales\n",
    "                if hasattr(type_element, 'GetMaterialIds'):\n",
    "                    material_ids = type_element.GetMaterialIds(False)\n",
    "                    if material_ids and len(material_ids) > 0:\n",
    "                        material = doc.GetElement(material_ids[0])\n",
    "                        if material:\n",
    "                            props[\"Material\"] = material.Name\n",
    "                            # Propiedades del material\n",
    "                            for mat_param in material.GetOrderedParameters():\n",
    "                                if mat_param.HasValue:\n",
    "                                    try:\n",
    "                                        props[f\"Material_{mat_param.Definition.Name}\"] = mat_param.AsDouble() if mat_param.StorageType == StorageType.Double else mat_param.AsString()\n",
    "                                    except:\n",
    "                                        continue\n",
    "    return props\n",
    "\n",
    "# --- Función para registrar nodos ---\n",
    "def register_node(point):\n",
    "    global node_counter\n",
    "    node_key = (round(point.X, 8), round(point.Y, 8), round(point.Z, 8))\n",
    "    if node_key not in node_dict:\n",
    "        node_dict[node_key] = {\n",
    "            \"id\": node_counter,\n",
    "            \"x\": point.X,\n",
    "            \"y\": point.Y,\n",
    "            \"z\": point.Z,\n",
    "            \"release_conditions\": []\n",
    "        }\n",
    "        analytical_data[\"nodes\"].append(node_dict[node_key])\n",
    "        node_counter += 1\n",
    "    return node_dict[node_key][\"id\"]\n",
    "\n",
    "# --- Recolectar Elementos Analíticos ---\n",
    "try:\n",
    "    element_collector = FilteredElementCollector(doc).OfClass(AnalyticalModel).WhereElementIsNotElementType().ToElements()\n",
    "    \n",
    "    for elem in element_collector:\n",
    "        if not elem.IsActive:\n",
    "            continue\n",
    "\n",
    "        # Información básica del elemento\n",
    "        element_info = {\n",
    "            \"id\": elem.Id.IntegerValue,\n",
    "            \"type\": None,\n",
    "            \"physical_info\": None\n",
    "        }\n",
    "\n",
    "        # Obtener elemento físico asociado\n",
    "        try:\n",
    "            association = elem.GetAnalyticalToPhysicalAssociation()\n",
    "            physical_element = doc.GetElement(association.GetAssociatedPhysicalElementId()) if association else None\n",
    "            if physical_element:\n",
    "                element_info[\"physical_info\"] = {\n",
    "                    \"id\": physical_element.Id.IntegerValue,\n",
    "                    \"properties\": get_element_properties(physical_element)\n",
    "                }\n",
    "        except Exception as e:\n",
    "            print(f\"Error obteniendo elemento físico para {elem.Id}: {str(e)}\")\n",
    "            element_info[\"physical_info\"] = None\n",
    "\n",
    "        # Procesar según el tipo de elemento analítico\n",
    "        try:\n",
    "            if isinstance(elem, AnalyticalModelFrame):\n",
    "                curve = elem.GetCurve()\n",
    "                if curve:\n",
    "                    start_id = register_node(curve.GetEndPoint(0))\n",
    "                    end_id = register_node(curve.GetEndPoint(1))\n",
    "                    \n",
    "                    element_info.update({\n",
    "                        \"type\": \"frame\",\n",
    "                        \"start_node_id\": start_id,\n",
    "                        \"end_node_id\": end_id,\n",
    "                        \"length\": curve.Length,\n",
    "                        \"curve_type\": str(curve.GetType().Name)\n",
    "                    })\n",
    "                    \n",
    "                    # Liberaciones\n",
    "                    try:\n",
    "                        releases = elem.GetAnalyticalRelease()\n",
    "                        if releases:\n",
    "                            element_info[\"start_release\"] = str(releases.Start)\n",
    "                            element_info[\"end_release\"] = str(releases.End)\n",
    "                    except:\n",
    "                        pass\n",
    "                    \n",
    "                    analytical_data[\"frames\"].append(element_info)\n",
    "            \n",
    "            elif isinstance(elem, AnalyticalModelSurface):\n",
    "                boundary_loops = elem.GetBoundaryLoops()\n",
    "                if boundary_loops:\n",
    "                    loops_info = []\n",
    "                    for loop in boundary_loops:\n",
    "                        loop_nodes = []\n",
    "                        for curve in loop:\n",
    "                            point = curve.GetEndPoint(0)\n",
    "                            node_id = register_node(point)\n",
    "                            loop_nodes.append(node_id)\n",
    "                        loops_info.append(loop_nodes)\n",
    "                    \n",
    "                    element_info.update({\n",
    "                        \"type\": \"shell\",\n",
    "                        \"loops\": loops_info\n",
    "                    })\n",
    "                    \n",
    "                    analytical_data[\"shells\"].append(element_info)\n",
    "        except Exception as e:\n",
    "            print(f\"Error procesando elemento {elem.Id}: {str(e)}\")\n",
    "            continue\n",
    "\n",
    "except Exception as e:\n",
    "    print(f\"Error en la recolección de elementos: {str(e)}\")\n",
    "    OUT = str(e)\n",
    "    sys.exit()\n",
    "\n",
    "# --- Salida ---\n",
    "try:\n",
    "    output_json = json.dumps(analytical_data, indent=4)\n",
    "    OUT = output_json\n",
    "except Exception as e:\n",
    "    OUT = f\"Error al generar JSON: {str(e)}\""
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
